curso/urls.py
from django.urls import path
from . import views

app_name = 'curso' 

urlpatterns = [
    path('', views.cursos, name='index'),
    path('curso/<int:curso_id>/', views.curso_detail_view, name='curso_detail'),
    path('projeto/<int:projeto_id>/', views.projeto_detail_view, name='projeto_detail'),
    path('new/', views.create_curso, name='curso_create'),
    path('edit/<int:pk>/', views.update_curso, name='curso_edit'),
    path('delete/<int:pk>/', views.delete_curso, name='curso_delete'),
    path('area-cientifica/create/', views.create_area_cientifica, name='area_cientifica_create'),
    path('area-cientifica/<int:pk>/update/', views.update_area_cientifica, name='area_cientifica_update'),
    path('area-cientifica/<int:pk>/delete/', views.delete_area_cientifica, name='area_cientifica_delete'),
    path('docente/create/', views.docente_create, name='docente_create'),
    path('docente/<int:pk>/update/', views.docente_update, name='docente_update'),
    path('docente/<int:pk>/delete/', views.docente_delete, name='docente_delete'),
    path('create/', views.create_disciplina, name='create_disciplina'),
    path('update/<int:pk>/', views.update_disciplina, name='update_disciplina'),
    path('disciplina/delete/<int:pk>/', views.delete_disciplina, name='delete_disciplina'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='allapps'),
    path('mebyme', views.mebyme, name='mebyme'),
    path('sobre', views.sobre, name='sobre'),
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('filmes/', include('filmes.urls')),
    path('curso/', include('curso.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('meteo/', include('meteo.urls')),
]

curso/models.py
from django.db import models

class Curso(models.Model):
    name = models.CharField(max_length=100)
    objectives = models.TextField()
    presentation = models.TextField()
    competences = models.TextField()

    def __str__(self):
        return self.name

class AreaCientifica(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Disciplina(models.Model):
    name = models.CharField(max_length=100)
    year = models.IntegerField()
    semester = models.CharField(max_length=100)
    ects = models.IntegerField()
    curricularIUnitReadableCode = models.CharField(max_length=100)
    scientificArea = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)
    course = models.ForeignKey(Curso, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Projeto(models.Model):
    disciplina = models.ForeignKey('Disciplina', on_delete=models.CASCADE)
    descricao = models.TextField()
    conceitos_aplicados = models.TextField()
    tecnologias_usadas = models.TextField()
    imagem = models.ImageField(upload_to='projeto_imagens/', null=True, blank=True)
    video_link = models.URLField(blank=True)
    github_repo_link = models.URLField(blank=True)
    language = models.ForeignKey('LinguagemDeProgramacao', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Projeto para {self.disciplina.name}"


class LinguagemDeProgramacao(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Docente(models.Model):
    nome = models.CharField(max_length=100)
    disciplinas = models.ManyToManyField('Disciplina', related_name='docentes')

    def __str__(self):
        return self.nome

curso/forms.py
from django import forms
from .models import Curso, AreaCientifica, Disciplina, Projeto, LinguagemDeProgramacao, Docente

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['name', 'objectives', 'presentation', 'competences']

class AreaCientificaForm(forms.ModelForm):
    class Meta:
        model = AreaCientifica
        fields = ['name']

class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = [
            'name', 'year', 'semester', 'ects', 
            'curricularIUnitReadableCode', 'scientificArea', 'course'
        ]

class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = [
            'disciplina', 'descricao', 'conceitos_aplicados', 
            'tecnologias_usadas', 'imagem', 'video_link', 
            'github_repo_link', 'language'
        ]

class LinguagemDeProgramacaoForm(forms.ModelForm):
    class Meta:
        model = LinguagemDeProgramacao
        fields = ['nome']

class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente
        fields = ['nome', 'disciplinas']

curso/views.py
from django.shortcuts import redirect, render
from curso.forms import *
from .models import *
from django.contrib.auth.decorators import login_required


class DisciplinaViewModel:
    def __init__(self, disciplina, projetos):
        self.info = disciplina
        self.projetos = projetos

def cursos(request):
    cursos = Curso.objects.all()
    return render(request, 'curso/cursos.html', {'cursos': cursos})

def curso_detail_view(request, curso_id):
    curso = Curso.objects.get(pk=curso_id)
    disciplinas = Disciplina.objects.filter(course = curso)
    disciplinasLista = []

    for d in disciplinas:
        disciplinasLista.append(DisciplinaViewModel(d, Projeto.objects.filter(disciplina = d)))

    return render(request, 'curso/curso_detail.html', {'curso': curso, 'disciplinasLista': disciplinasLista})


def projeto_detail_view(request, projeto_id):
    projeto = Projeto.objects.get(pk=projeto_id)
    return render(request, 'curso/projeto_detail.html', {'projeto': projeto})

@login_required
def create_curso(request):
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:index')  
    else:
        form = CursoForm()
    return render(request, 'curso/curso_form.html', {'form': form})

@login_required
def update_curso(request, pk):
    curso = Curso.objects.get(pk=pk)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('curso:index') 
    else:
        form = CursoForm(instance=curso)
    return render(request, 'curso/curso_form.html', {'form': form})

@login_required
def delete_curso(request, pk):
    curso = Curso.objects.get(pk=pk)
    if request.method == 'POST':
        curso.delete()
        return redirect('curso:index')  
    return render(request, 'curso/curso_confirm_delete.html', {'curso': curso})

@login_required
def create_area_cientifica(request):
    if request.method == 'POST':
        form = AreaCientificaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:index')
    else:
        form = AreaCientificaForm()
    return render(request, 'curso/area_cientifica_form.html', {'form': form})

@login_required
def update_area_cientifica(request, pk):
    area_cientifica = AreaCientifica.objects.get(pk=pk)
    if request.method == 'POST':
        form = AreaCientificaForm(request.POST, instance=area_cientifica)
        if form.is_valid():
            form.save()
            return redirect('curso:index')
    else:
        form = AreaCientificaForm(instance=area_cientifica)
    return render(request, 'curso/area_cientifica_form.html', {'form': form})

@login_required
def delete_area_cientifica(request, pk):
    area_cientifica = AreaCientifica.objects.get(pk=pk)
    if request.method == 'POST':
        area_cientifica.delete()
        return redirect('curso:index')
    return render(request, 'curso/area_cientifica_confirm_delete.html', {'object': area_cientifica})

@login_required
def docente_create(request):
    if request.method == 'POST':
        form = DocenteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:index')  # Change this to your desired URL name
    else:
        form = DocenteForm()
    return render(request, 'curso/docente_form.html', {'form': form})

@login_required
def docente_update(request, pk):
    docente = Docente.objects.get(pk=pk)
    if request.method == 'POST':
        form = DocenteForm(request.POST, instance=docente)
        if form.is_valid():
            form.save()
            return redirect('curso:index')  
    else:
        form = DocenteForm(instance=docente)
    return render(request, 'curso/docente_form.html', {'form': form})

@login_required
def docente_delete(request, pk):
    docente = Docente.objects.get(pk=pk)
    if request.method == 'POST':
        docente.delete()
        return redirect('curso:index')  
    return render(request, 'curso/docente_confirm_delete.html', {'object': docente})


@login_required
def create_disciplina(request):
    if request.method == 'POST':
        form = DisciplinaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:index')
    else:
        form = DisciplinaForm()
    return render(request, 'curso/disciplina_form.html', {'form': form})

@login_required
def update_disciplina(request, pk):
    disciplina = Disciplina.objects.get(pk=pk)

    if request.method == 'POST':
        form = DisciplinaForm(request.POST, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('curso:index')
    else:
        form = DisciplinaForm(instance=disciplina)
    return render(request, 'curso/disciplina_form.html', {'form': form})

@login_required
def delete_disciplina(request, pk):
    disciplina = Disciplina.objects.get(pk=pk)
    if request.method == 'POST':
        disciplina.delete()
        return redirect('curso:index')
    return render(request, 'curso/disciplina_confirm_delete.html', {'disciplina': disciplina})

curso/templates/curso/area_cientifica_confirm_delete.html
{% extends 'base_layout.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete "{{ object.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

curso/templates/curso/area_cientifica_form.html
{% extends 'base_layout.html' %}

{% block title %}Area Cientifica Form{% endblock %}

{% block content %}
    <h1>{% block heading %}{% endblock %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

curso/templates/curso/curso_confirm_delete.html
{% extends 'base_layout.html' %}
{% block content %}
  <h2>Confirm Delete</h2>
  <p>Are you sure you want to delete "{{ curso.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

curso/templates/curso/curso_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>{{ curso.name }}a</h2>
    {% if request.user.is_authenticated %}
    <p class="forms-buttons">
        <a href="{% url 'curso:curso_edit' curso.id  %}">Editar curso</a>
        <a href="{% url 'curso:curso_delete' curso.id  %}">Apagar curso</a>
    </p>
    {% endif %}

    <div class="discipline-cards">
        {% for disciplina in disciplinasLista %}
            <div class="card {% if disciplina.projetos %}has-projects{% endif %}">
                <div class="card-header">
                    {{ disciplina.info.name }} ({{ disciplina.info.year }}º ano/{{ disciplina.info.semester }})
                </div>
                {% if request.user.is_authenticated %}
                <p class="forms-buttons">
                    <a href="{% url 'curso:update_disciplina' disciplina.info.id  %}">Editar</a>
                    <a href="{% url 'curso:delete_disciplina' disciplina.info.id  %}">Apagar</a>
                </p>
                {% endif %}

                <div class="card-body">
                    <ul>
                        <li>ECTS: {{ disciplina.info.ects }}</li>
                        <li>Curricular Unit Readable Code: {{ disciplina.info.curricularIUnitReadableCode }}</li>
                        <li>Scientific Area: {{ disciplina.info.scientificArea.name }}</li>
                        {% if disciplina.projetos %}
                            <li style="padding: 0px 5px 5px 5px;">Projects:</li>
                            <ul style="margin-left: 15px; border-left: 2px solid blue; padding-left: 10px;">
                                {% for projeto in disciplina.projetos %}
                                    <li>
                                        <a href="{% url 'curso:projeto_detail' projeto.id %}">
                                            <strong>{{ projeto.descricao }}</strong>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                            
                        {% endif %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block style %}
<style>
    .discipline-cards {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }
    .card {
        background-color: #f9f9f9;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
        width: 90%;
        padding: 20px;
    }
    .card-header {
        font-weight: bold;
        margin-bottom: 10px;
    }
    .card-body ul {
        list-style: none;
        padding: 0;
    }
    .card-body ul li {
        margin-bottom: 5px;
    }
    .card-body ul li a {
        color: blueviolet;
        text-decoration: none;
        font-weight: bold;
    }
    .card-body ul li a:hover {
        color: #333;
    }

    .card.has-projects {
        background-color: lightgreen;
    }

    @media screen and (max-width: 768px) {
        .card {
            width: calc(50% - 20px);
        }
    }
    @media screen and (max-width: 480px) {
        .card {
            width: calc(100% - 20px);
        }
    }
</style>

{% endblock %}

curso/templates/curso/curso_form.html
{% extends 'base_layout.html' %}
{% block content %}
  <h2>Create or Update Curso</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

curso/templates/curso/cursos.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Todos os Cursos Disponíveis</h1>
<ul class="curso-list">
    {% for curso in cursos %}
    <li><a href="{% url 'curso:curso_detail' curso.id %}">{{ curso.name }}</a></li>
    {% endfor %}
</ul>
{% if user.is_authenticated %}
<p class="forms-buttons">
    <a href="{% url 'curso:curso_create'  %}">Criar novo curso</a>
    <a href="{% url 'curso:area_cientifica_create'  %}">Criar nova area cientifica</a>
    <a href="{% url 'curso:docente_create'  %}">Criar novo docente</a>
    <a href="{% url 'curso:create_disciplina'  %}">Criar nova disciplina</a>
</p>
{% endif %}
{% endblock content %}

{% block style %}
<style>
    /* Styles for Curso List */
    .curso-list {
        list-style: none;
        padding: 0;
        margin: 20px 0;
    }

    .curso-list li {
        margin-bottom: 10px;
    }

    .curso-list li a {
        text-decoration: none;
        color: #333;
        font-weight: bold;
        transition: color 0.3s ease;
    }

    .curso-list li a:hover {
        color: #666;
    }

    /* Media query for responsiveness */
    @media screen and (max-width: 768px) {
        .curso-list {
            margin: 10px 0;
        }

        .curso-list li {
            margin-bottom: 5px;
        }
    }
</style>
{% endblock style %}

curso/templates/curso/disciplina_confirm_delete.html
{% extends 'base_layout.html' %}

{% block content %}
  <h2>Delete Disciplina</h2>
  <p>Are you sure you want to delete "{{ disciplina.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
  </form>
{% endblock %}

curso/templates/curso/disciplina_form.html
{% extends 'base_layout.html' %}

{% block content %}
  <h2>{% if form.instance.pk %}Update{% else %}Create{% endif %} Disciplina</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

curso/templates/curso/docente_confirm_delete.html
{% extends 'base_layout.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete "{{ object.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

curso/templates/curso/docente_form.html
{% extends 'base_layout.html' %}

{% block title %}Docente Form{% endblock %}

{% block content %}
    <h1>{% block heading %}{% endblock %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

curso/templates/curso/projeto_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="project-container">
        <h1>{{ projeto.descricao }}</h1>
        <div class="project-details">
            <p><strong>Disciplina:</strong> {{ projeto.disciplina.name }}</p>
            <p><strong>Concepts Applied:</strong> {{ projeto.conceitos_aplicados }}</p>
            <p><strong>Technologies Used:</strong> {{ projeto.tecnologias_usadas }}</p>
        </div>
        {% if projeto.imagem %}
            <img src="{{ projeto.imagem.url }}" alt="Project Image">
        {% endif %}
        <div class="project-links">
            {% if projeto.video_link %}
                <p><strong>Video Link:</strong> <a href="{{ projeto.video_link }}">{{ projeto.video_link }}</a></p>
            {% endif %}
            {% if projeto.github_repo_link %}
                <p><strong>GitHub Repository:</strong> <a href="{{ projeto.github_repo_link }}">{{ projeto.github_repo_link }}</a></p>
            {% endif %}
            {% if projeto.language %}
                <p><strong>Programming Language:</strong> {{ projeto.language.nome }}</p>
            {% endif %}
        </div>
    </div>

{% endblock content %}