bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.band_list_view, name='index'),
    path('band/<int:band_id>/', views.band_detail_view, name='band_detail'),
    path('album/<int:album_id>/', views.album_view, name='album_detail'),
    path('song/<int:song_id>/', views.song_details, name='song_detail'),
    path('song/create/', views.createSong, name='create_song'),
    path('band/create/', views.createBand, name='create_band'),
    path('album/create/', views.createAlbum, name='create_album'),
    path('album/<int:album_id>/edit/', views.edit_album, name='edit_album'),
    path('band/<int:band_id>/edit/', views.edit_band, name='edit_band'),
    path('song/<int:song_id>/edit/', views.edit_song, name='edit_song'),
    path('song/<int:song_id>/delete/', views.delete_song, name='delete_song'),
    path('band/<int:band_id>/delete/', views.delete_band, name='delete_band'),
    path('album/<int:album_id>/delete/', views.delete_album, name='delete_album'),

]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso' 

urlpatterns = [
    path('', views.cursos, name='index'),
    path('curso/<int:curso_id>/', views.curso_detail_view, name='curso_detail'),
    path('projeto/<int:projeto_id>/', views.projeto_detail_view, name='projeto_detail'),
    path('new/', views.create_curso, name='curso_create'),
    path('edit/<int:pk>/', views.update_curso, name='curso_edit'),
    path('delete/<int:pk>/', views.delete_curso, name='curso_delete'),
    path('area-cientifica/create/', views.create_area_cientifica, name='area_cientifica_create'),
    path('area-cientifica/<int:pk>/update/', views.update_area_cientifica, name='area_cientifica_update'),
    path('area-cientifica/<int:pk>/delete/', views.delete_area_cientifica, name='area_cientifica_delete'),
    path('docente/create/', views.docente_create, name='docente_create'),
    path('docente/<int:pk>/update/', views.docente_update, name='docente_update'),
    path('docente/<int:pk>/delete/', views.docente_delete, name='docente_delete'),
    path('create/', views.create_disciplina, name='create_disciplina'),
    path('update/<int:pk>/', views.update_disciplina, name='update_disciplina'),
    path('disciplina/delete/<int:pk>/', views.delete_disciplina, name='delete_disciplina'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='allapps'),
    path('mebyme', views.mebyme, name='mebyme'),
    path('sobre', views.sobre, name='sobre'),
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('artigos/', include('artigos.urls')),
    path('filmes/', include('filmes.urls')),
    path('curso/', include('curso.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('biblioteca/', include('biblioteca.urls')),
    path('meteo/', include('meteo.urls')),
]

bandas/models.py
from django.db import models

class Band(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    formed_in = models.IntegerField()
    photo = models.ImageField(upload_to='banda_imagens/', blank=True, null=True)
    info = models.TextField()
    nacionality = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=100)
    release_year = models.IntegerField()
    cover = models.ImageField(upload_to='banda_imagens/', blank=True, null=True)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Song(models.Model):
    title = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    spotify_link = models.URLField(blank=True, null=True)
    duration = models.CharField(max_length=100)
    letra = models.TextField(default='', null=True, blank=True)
    biografia = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return self.title


bandas/forms.py
from django import forms
from .models import *

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'album', 'spotify_link', 'duration', 'letra', 'biografia']
        help_texts = {
            'title': 'Insira o título da música.',
            'album': 'Selecione o álbum ao qual a música pertence.',
            'spotify_link': 'Insira o link do Spotify da música (opcional).',
            'duration': 'Insira a duração da música.',
            'letra': 'Insira a letra da música (opcional).',
            'biografia': 'Insira uma biografia curta da música (opcional).'
        }
        
class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = ['name', 'genre', 'formed_in', 'photo', 'info', 'nacionality']
        help_texts = {
            'name': 'Insira o nome da banda.',
            'genre': 'Insira o gênero musical da banda.',
            'formed_in': 'Insira o ano de formação da banda.',
            'photo': 'Selecione uma foto da banda.',
            'info': 'Insira informações adicionais sobre a banda.',
            'nacionality': 'Insira a nacionalidade da banda.'
        }

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'release_year', 'cover', 'band']
        help_texts = {
            'title': 'Insira o título do álbum.',
            'release_year': 'Insira o ano de lançamento do álbum.',
            'cover': 'Selecione a capa do álbum.',
            'band': 'Selecione a banda associada ao álbum.'
        }

bandas/views.py
from django.shortcuts import render, redirect
from .models import Band, Album, Song
from .forms import SongForm, BandForm, AlbumForm
from django.contrib.auth.decorators import login_required

def index_view(request):
    context = {}
    return render(request, 'bandas/index.html', context)

def band_list_view(request):
    bands = Band.objects.all()
    context = {'bands': bands}
    return render(request, 'bandas/bands.html', context)

def album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    songs = Song.objects.filter(album=album)
    context = {'album': album, 'songs': songs}
    return render(request, 'bandas/album.html', context)

def song_details(request, song_id):
    song = Song.objects.get(id=song_id)
    album = Album.objects.get(song = song)
    context = {'song': song, 'album' : album}

    return render(request, 'bandas/song_details.html', context)

def band_detail_view(request, band_id):
    band = Band.objects.get(pk=band_id)
    albuns = Album.objects.filter(band=band)
    context = {'band': band, 'albums': albuns}
    return render(request, 'bandas/band_detail.html', context)

@login_required
def createSong(request):
    if request.method == 'POST':
        form = SongForm(request.POST)
        if form.is_valid():
            song = form.save(commit=False)
            song.save()
            return redirect('bandas:song_detail', song_id=song.id)
    else:
        form = SongForm()
    
    return render(request, 'bandas/create_song.html', {'form': form})

@login_required
def createBand(request):
    if request.method == 'POST':
        form = BandForm(request.POST, request.FILES)
        if form.is_valid():
            band = form.save(commit=False)
            band.save()
            return redirect('bandas:band_detail', band_id=band.id)
    else:
        form = BandForm()
    
    return render(request, 'bandas/create_band.html', {'form': form})

@login_required
def createAlbum(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            album = form.save(commit=False)
            album.save()
            return redirect('bandas:album_detail', album_id=album.id)
    else:
        form = AlbumForm()
    
    return render(request, 'bandas/create_album.html', {'form': form})

@login_required
def edit_song(request, song_id):
    song = Song.objects.get(id=song_id)
    if request.method == 'POST':
        form = SongForm(request.POST, instance=song)
        if form.is_valid():
            form.save()
            return redirect('bandas:song_detail', song_id=song.id)
    else:
        form = SongForm(instance=song)
    return render(request, 'bandas/edit_song.html', {'form': form})

@login_required
def edit_band(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, request.FILES, instance=band)
        if form.is_valid():
            form.save()
            return redirect('bandas:band_detail', band_id=band.id)
    else:
        form = BandForm(instance=band)
    return render(request, 'bandas/edit_band.html', {'form': form})

@login_required
def edit_album(request, album_id):
    album = Album.objects.get(id=album_id)
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:album_detail', album_id=album.id)
    else:
        form = AlbumForm(instance=album)
    return render(request, 'bandas/edit_album.html', {'form': form})

@login_required
def delete_song(request, song_id):
    song = Song.objects.get(id=song_id)
    if request.method == 'POST':
        song.delete()
        return redirect('bandas:index')
    return render(request, 'bandas/delete_songs.html', {'song': song})

@login_required
def delete_band(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        band.delete()
        return redirect('bandas:index')
    return render(request, 'bandas/delete_band.html', {'band': band})

@login_required
def delete_album(request, album_id):
    album = Album.objects.get(id=album_id)
    if request.method == 'POST':
        album.delete()
        return redirect('bandas:index')
    return render(request, 'bandas/delete_album.html', {'album': album})
 



bandas/templates/bandas/album.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="listSomething">

<ul>
    <h3>Album: {{ album.title }}, {{ album.release_year }}</h3>
    <p>Lista de músicas do álbum:</p>
    <ul>
        {% for song in songs %}
        <li>
            <a href="{% url 'bandas:song_detail' song.id %}">{{ song.title }}</a>
            {% if song.letra %}
                <i class="fa-solid fa-music"></i>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</ul>
</div>
{% if request.user.is_authenticated %}
<div class="forms-buttons">
    <a href="{% url 'bandas:edit_album' album.id %}">Edit</a>
    <a href="{% url 'bandas:delete_album' album.id %}">Delete</a>
</div>
{% endif %}
{% endblock content %}

bandas/templates/bandas/band_detail.html
{% extends 'base_layout.html' %}
{% block content %}

<h1>{{ band.name }}</h1>

<div class="band-details">
  <p>Gênero: {{ band.genre }}</p>
  <p>Ano de formação: {{ band.formed_in }}</p>
  <p>Nacionalidade: {{ band.nacionality }}</p>

  {% if band.photo %}
  <img src="{{ band.photo.url }}" alt="Foto da banda {{ band.name }}">
  {% else %}
  <p>Imagem da banda não disponível.</p>
  {% endif %}

  <p>{{ band.info }}</p>
</div>
{% if request.user.is_authenticated %}
<div class="forms-buttons">
  <a href="{% url 'bandas:edit_band' band.id %}">Edit</a>
  <a href="{% url 'bandas:delete_band' band.id %}">Delete</a>
</div>
{% endif %}

<h2>Discografia</h2>
<div class="listSomething">
  <ul>
    {% for album in albums %}
    <li>
      <a href="{% url 'bandas:album_detail' album.pk %}">{{ album.title }}</a> ({{ album.release_year }})
      {% if album.cover %}
      <img src="{{ album.cover.url }}" alt="Capa do álbum {{ album.title }}" width="100">
      {% endif %}
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

bandas/templates/bandas/bands.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Bands</h1>
<div class="listSomething">
<ul>
  {% for band in bands %}
    <li><a href="{% url 'bandas:band_detail' band.id %}">{{ band.name }}</a></li>  {% endfor %}
</ul>
</div>
{% if request.user.is_authenticated %}
<p class="forms-buttons" >
  <a href="{% url 'bandas:create_band'  %}" >Create New Band</a>
  <a href="{% url 'bandas:create_album'  %}" >Create New Album</a>
  <a href="{% url 'bandas:create_song'  %}" >Create New Song</a>
</p>
{% endif %}

<!-- Seções com padrões -->
<section class="section-pattern-1">
  <h2>Seção com Padrão 1</h2>
  <p>Conteúdo da seção 1.</p>
</section>
<section class="section-pattern-2">
  <h2>Seção com Padrão 2</h2>
  <p>Conteúdo da seção 2.</p>
</section>
<section class="section-pattern-3">
  <h2>Seção com Padrão 3</h2>
  <p>Conteúdo da seção 3.</p>
</section>

{% endblock %}

bandas/templates/bandas/create_album.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Create New Album</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/create_band.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Create New Band</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/create_song.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Create New Song</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/delete_album.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Delete Album</h1>
  <p>Are you sure you want to delete "{{ album.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'bandas:album_detail' album_id=album.id %}">Cancel</a>
  </form>
{% endblock %}

bandas/templates/bandas/delete_band.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Delete Band</h1>
  <p>Are you sure you want to delete "{{ band.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'bandas:band_detail' band_id=band.id %}">Cancel</a>
  </form>
{% endblock %}

bandas/templates/bandas/delete_songs.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Delete Song</h1>
  <p>Are you sure you want to delete "{{ song.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'bandas:song_detail' song_id=song.id %}">Cancel</a>
  </form>
{% endblock %}

bandas/templates/bandas/edit_album.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Edit Album</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/edit_band.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Edit Band</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/edit_song.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Edit Song</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="helptext">
    {% for field in form %}
    {{ field.help_text }}
    {% endfor %}
  </div>
  <button type="submit">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/html5-css.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Seletores CSS</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h3>Seletores CSS</h3>
    <p>Os seletores CSS são utilizados para direcionar elementos específicos em uma página da web e aplicar estilos a eles.</p>
    <table>
        <tr>
            <th>Tipo de Seletor</th>
            <th>Utilizado?</th>
            <th>Comentário</th>
        </tr>
        <tr>
            <td>Seletor de Elemento</td>
            <td><i class="material-icons">done</i></td>
            <td>Seleciona elementos com base em seu tipo (tag), como `<p>` ou `<div>`. É amplamente utilizado em todas as páginas HTML.</td>
        </tr>
        <tr>
            <td>Seletor de Classe</td>
            <td><i class="material-icons">done</i></td>
            <td>Seleciona elementos com base em sua classe atribuída. É comumente usado para aplicar estilos a elementos específicos com a mesma classe.</td>
        </tr>
        <!-- Adicione mais linhas conforme necessário para outros seletores -->
    </table>

    <h3>Combinadores de Seletores</h3>
    <table>
        <tr>
            <th>Combinador</th>
            <th>Utilizado?</th>
            <th>Comentário</th>
        </tr>
        <tr>
            <td>Descendente (espaço)</td>
            <td><i class="material-icons">done</i></td>
            <td>Seleciona um elemento que é descendente de outro elemento especificado. É comumente usado para aplicar estilos a elementos filhos de um elemento pai específico.</td>
        </tr>
        <tr>
            <td>Seletor de Filho Direto (&gt;)</td>
            <td><i class="material-icons">done</i></td>
            <td>Seleciona um elemento que é um filho direto de outro elemento especificado. É útil quando você deseja estilizar apenas os filhos diretos de um elemento pai.</td>
        </tr>
    </table>
</body>
</html>

bandas/templates/bandas/song_details.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Song: {{ song.title }}</h1>
    <ul>
        <li>{{ song.title }}</li>
        <li><a href="{{spotify_link}}">Listen in spotify</a></li>
        <li>Duration: {{ song.duration }}</li>
        <li>Letra: <p>{{ song.letra }}</p></li>
    </ul>
    <div class="biografia">
        {{ banda.biografia }}
    </div>
    {% if request.user.is_authenticated %}
    <div class="forms-buttons">
        <a href="{% url 'bandas:edit_song' song.id %}" >Edit</a>
        <a href="{% url 'bandas:delete_song' song.id %}">Delete</a>
    </div>
    {% endif %}

    <a href="{% url 'bandas:album_detail' album.id %}">Go back to the album: {{ album.title }}</a>


{% endblock %}